version: "3"
services:
  mysql:
    image: circleci/mysql:5.7
    restart: always
    volumes:
      - .misc/mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ubuntu
      MYSQL_PASSWORD: ubuntu
      MYSQL_DATABASE: app
  app:
    build: .
    depends_on:
      - mysql
  nginx:
    build: docker/nginx/.
    ports:
      - 8000:80
    depends_on:
      - app
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - 80:80
      - 443:443
    restart: always
    environment:
      DOMAINS: 'api.local -> http://nginx:80'
      STAGE: local
    volumes:
      - .misc/certs:/var/lib/https-portal
